-----BEGIN PRIVATE KEY-----

THIS SHOULD BE YOUR P8 GENERATED CERTIFICATE VIA THE APPLE DEVELOPER CONSOLE.
OVERWRITE THIS FILE WITH YOUR CERTIFICATE FILE AND NAME IT IDENTICALLY TO WHAT YOU SET IN
app.js.

-----END PRIVATE KEY-----
